"""Phase 5.2: security event monitoring

Revision ID: 3beb4081d2a8
Revises: 194f03c6cbca
Create Date: 2025-12-30 17:11:40.545309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3beb4081d2a8'
down_revision = '194f03c6cbca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=80), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('email_masked', sa.String(length=255), nullable=True),
    sa.Column('endpoint', sa.String(length=160), nullable=True),
    sa.Column('path', sa.String(length=300), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_event_email_masked'), ['email_masked'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_event_endpoint'), ['endpoint'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_event_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_event_ip'), ['ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_event_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_event_status'))
        batch_op.drop_index(batch_op.f('ix_security_event_ip'))
        batch_op.drop_index(batch_op.f('ix_security_event_event'))
        batch_op.drop_index(batch_op.f('ix_security_event_endpoint'))
        batch_op.drop_index(batch_op.f('ix_security_event_email_masked'))
        batch_op.drop_index(batch_op.f('ix_security_event_created_at'))

    op.drop_table('security_event')
    # ### end Alembic commands ###
