"""initial tables

Revision ID: 6a4c2db6880d
Revises: 
Create Date: 2025-12-26 01:33:33.560604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4c2db6880d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('passed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('uq_user_topic'), type_='unique')
        batch_op.create_unique_constraint('uq_progress_user_slug', ['user_id', 'slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_constraint('uq_progress_user_slug', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_topic'), ['user_id', 'slug'])
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('passed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('slug',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###
