"""add security_event table

Revision ID: 98675f43c0ac
Revises: 3beb4081d2a8
Create Date: 2025-12-30 18:22:36.851558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98675f43c0ac'
down_revision = '3beb4081d2a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_event', schema=None) as batch_op:
        batch_op.alter_column('endpoint',
               existing_type=sa.VARCHAR(length=160),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('path',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('method',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=12),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_security_event_email_masked'))
        batch_op.create_index(batch_op.f('ix_security_event_path'), ['path'], unique=False)
        batch_op.drop_column('email_masked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_masked', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_index(batch_op.f('ix_security_event_path'))
        batch_op.create_index(batch_op.f('ix_security_event_email_masked'), ['email_masked'], unique=False)
        batch_op.alter_column('method',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('path',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('endpoint',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=160),
               existing_nullable=True)

    # ### end Alembic commands ###
