"""Add Job model

Revision ID: 9b0111b3d69f
Revises: a1b2c3d4e5f6
Create Date: 2026-04-07 10:49:17.846710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b0111b3d69f'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('job_type', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_job_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_posted_at'), ['posted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_title'), ['title'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['referred_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_title'))
        batch_op.drop_index(batch_op.f('ix_job_posted_at'))
        batch_op.drop_index(batch_op.f('ix_job_is_active'))
        batch_op.drop_index(batch_op.f('ix_job_external_id'))

    op.drop_table('job')
    # ### end Alembic commands ###
