"""add exam_attempt table

Revision ID: cc896c1dac53
Revises: 9b0111b3d69f
Create Date: 2026-04-08 20:05:35.428337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc896c1dac53'
down_revision = '9b0111b3d69f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exam_set', sa.String(length=64), nullable=False),
    sa.Column('score_pct', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('elapsed_secs', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_attempt_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['referred_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('exam_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_attempt_user_id'))

    op.drop_table('exam_attempt')
    # ### end Alembic commands ###
