"""add certificate revocation fields

Revision ID: e7b41b44c934
Revises: f6e0370cc240
Create Date: 2025-12-29 08:05:53.021283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7b41b44c934'
down_revision = 'f6e0370cc240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revoked', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('revoked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('revoked_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.drop_column('revoked_reason')
        batch_op.drop_column('revoked_at')
        batch_op.drop_column('revoked')

    # ### end Alembic commands ###
