"""add certificate table

Revision ID: f6e0370cc240
Revises: f0059c2dcce9
Create Date: 2025-12-28 03:00:04.322386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e0370cc240'
down_revision = 'f0059c2dcce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cert_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('recipient_name', sa.String(length=120), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificate_cert_id'), ['cert_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_certificate_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificate_user_id'))
        batch_op.drop_index(batch_op.f('ix_certificate_cert_id'))

    op.drop_table('certificate')
    # ### end Alembic commands ###
